### ISSUE TITLE
New automatedSearch and feeds directives do not survive minification

### ISSUE THREAD

**Issue by dfernandezm** [dfernandezm/download-utils#108]
The JS minification through Uglify JS breaks the code of these two directives. Investigate in which part this breaks as they were developed following a common practice to avoid this issue, but it seems both are broken when minified.

**Comment by dfernandezm** [comment]
```
Error: [$injector:unpr] http://errors.angularjs.org/1.3.18/$injector/unpr?p0=tProvider%20%3C-%20t%20%3C-%20Feed%20%3C-%20feedsDirective
    at Error (native)
    at http://download-utils/client/js/app/init.js:1:24463
    at http://download-utils/client/js/app/init.js:2:8390
    at Object.r [as get] (http://download-utils/client/js/app/init.js:2:7359)
    at http://download-utils/client/js/app/init.js:2:8463
    at r (http://download-utils/client/js/app/init.js:2:7359)
    at Object.i [as invoke] (http://download-utils/client/js/app/init.js:2:7626)
    at Object.$get (http://download-utils/client/js/app/init.js:2:6592)
    at Object.i [as invoke] (http://download-utils/client/js/app/init.js:2:7659)
    at http://download-utils/client/js/app/init.js:2:8492(anonymous function) @ init.js:3
```

**Comment by dfernandezm** [comment]
Suggested by @fniewijk:

Wrap the directive call with brackets `()`, like this:

```
directive ('feeds', ['Feed', 'feedsService', (Feed, feedsService) -> .... ])
```

**Comment by dfernandezm** [comment]
The problem ended up being the mod.inject call inside feedResource.coffee and automatedSearchResource.coffee which does survive minification. The injection of $resource service has to happen when the factory is actually instantiated.
